<?php
/*Source: https://www.php.de/forum/l%C3%B6sungen-durch-skripte/
scriptb%C3%B6rse/60455-alle-l%C3%A4nderk%C3%BCrzel-deutsch-englisch-als-array*/
//'de' geaendert zu "0" und "en" zu "1" fuer kompatibilitaet mit SESSION->lanuage auswahl
$laender[1]['AF'] = "Afghanistan";
$laender[0]['AF'] = "Afghanistan";
$laender[1]['AL'] = "Albania";
$laender[0]['AL'] = "Albanien";
$laender[1]['AS'] = "American Samoa";
$laender[0]['AS'] = "Amerikanisch Samoa";
$laender[1]['AD'] = "Andorra";
$laender[0]['AD'] = "Andorra";
$laender[1]['AO'] = "Angola";
$laender[0]['AO'] = "Angola";
$laender[1]['AI'] = "Anguilla";
$laender[0]['AI'] = "Anguilla";
$laender[1]['AQ'] = "Antarctica";
$laender[0]['AQ'] = "Antarktis";
$laender[1]['AG'] = "Antigua and Barbuda";
$laender[0]['AG'] = "Antigua und Barbuda";
$laender[1]['AR'] = "Argentina";
$laender[0]['AR'] = "Argentinien";
$laender[1]['AM'] = "Armenia";
$laender[0]['AM'] = "Armenien";
$laender[1]['AW'] = "Aruba";
$laender[0]['AW'] = "Aruba";
$laender[1]['AT'] = "Austria";
$laender[0]['AT'] = "Österreich";
$laender[1]['AU'] = "Australia";
$laender[0]['AU'] = "Australien";
$laender[1]['AZ'] = "Azerbaijan";
$laender[0]['AZ'] = "Aserbaidschan";
$laender[1]['BS'] = "Bahamas";
$laender[0]['BS'] = "Bahamas";
$laender[1]['BH'] = "Bahrain";
$laender[0]['BH'] = "Bahrain";
$laender[1]['BD'] = "Bangladesh";
$laender[0]['BD'] = "Bangladesh";
$laender[1]['BB'] = "Barbados";
$laender[0]['BB'] = "Barbados";
$laender[1]['BY'] = "Belarus";
$laender[0]['BY'] = "Weißrussland";
$laender[1]['BE'] = "Belgium";
$laender[0]['BE'] = "Belgien";
$laender[1]['BZ'] = "Belize";
$laender[0]['BZ'] = "Belize";
$laender[1]['BJ'] = "Benin";
$laender[0]['BJ'] = "Benin";
$laender[1]['BM'] = "Bermuda";
$laender[0]['BM'] = "Bermuda";
$laender[1]['BT'] = "Bhutan";
$laender[0]['BT'] = "Bhutan";
$laender[1]['BO'] = "Bolivia";
$laender[0]['BO'] = "Bolivien";
$laender[1]['BA'] = "Bosnia and Herzegovina";
$laender[0]['BA'] = "Bosnien Herzegowina";
$laender[1]['BW'] = "Botswana";
$laender[0]['BW'] = "Botswana";
$laender[1]['BV'] = "Bouvet Island";
$laender[0]['BV'] = "Bouvet Island";
$laender[1]['BR'] = "Brazil";
$laender[0]['BR'] = "Brasilien";
$laender[1]['BN'] = "Brunei Darussalam";
$laender[0]['BN'] = "Brunei Darussalam";
$laender[1]['BG'] = "Bulgaria";
$laender[0]['BG'] = "Bulgarien";
$laender[1]['BF'] = "Burkina Faso";
$laender[0]['BF'] = "Burkina Faso";
$laender[1]['BI'] = "Burundi";
$laender[0]['BI'] = "Burundi";
$laender[1]['KH'] = "Cambodia";
$laender[0]['KH'] = "Kambodscha";
$laender[1]['CM'] = "Cameroon";
$laender[0]['CM'] = "Kamerun";
$laender[1]['CA'] = "Canada";
$laender[0]['CA'] = "Kanada";
$laender[1]['CV'] = "Cape Verde";
$laender[0]['CV'] = "Kap Verde";
$laender[1]['KY'] = "Cayman Islands";
$laender[0]['KY'] = "Cayman Inseln";
$laender[1]['CF'] = "Central African Republic";
$laender[0]['CF'] = "Zentralafrikanische Republik";
$laender[1]['TD'] = "Chad";
$laender[0]['TD'] = "Tschad";
$laender[1]['CL'] = "Chile";
$laender[0]['CL'] = "Chile";
$laender[1]['CN'] = "China";
$laender[0]['CN'] = "China";
$laender[1]['CO'] = "Colombia";
$laender[0]['CO'] = "Kolumbien";
$laender[1]['KM'] = "Comoros";
$laender[0]['KM'] = "Comoros";
$laender[1]['CG'] = "Congo";
$laender[0]['CG'] = "Kongo";
$laender[1]['CK'] = "Cook Islands";
$laender[0]['CK'] = "Cook Inseln";
$laender[1]['CR'] = "Costa Rica";
$laender[0]['CR'] = "Costa Rica";
$laender[1]['CI'] = "Côte d'Ivoire";
$laender[0]['CI'] = "Elfenbeinküste";
$laender[1]['HR'] = "Croatia";
$laender[0]['HR'] = "Kroatien";
$laender[1]['CU'] = "Cuba";
$laender[0]['CU'] = "Kuba";
$laender[1]['CZ'] = "Czech Republic";
$laender[0]['CZ'] = "Tschechien";
$laender[1]['DK'] = "Denmark";
$laender[0]['DK'] = "Dänemark";
$laender[1]['DJ'] = "Djibouti";
$laender[0]['DJ'] = "Djibouti";
$laender[1]['DO'] = "Dominican Republic";
$laender[0]['DO'] = "Dominikanische Republik";
$laender[1]['TP'] = "East Timor";
$laender[0]['TP'] = "Osttimor";
$laender[1]['EC'] = "Ecuador";
$laender[0]['EC'] = "Ecuador";
$laender[1]['EG'] = "Egypt";
$laender[0]['EG'] = "Ägypten";
$laender[1]['SV'] = "El salvador";
$laender[0]['SV'] = "El Salvador";
$laender[1]['GQ'] = "Equatorial Guinea";
$laender[0]['GQ'] = "Äquatorial Guinea";
$laender[1]['ER'] = "Eritrea";
$laender[0]['ER'] = "Eritrea";
$laender[1]['EE'] = "Estonia";
$laender[0]['EE'] = "Estland";
$laender[1]['ET'] = "Ethiopia";
$laender[0]['ET'] = "Äthiopien";
$laender[1]['FK'] = "Falkland Islands";
$laender[0]['FK'] = "Falkland Inseln";
$laender[1]['FO'] = "Faroe Islands";
$laender[0]['FO'] = "Faroe Inseln";
$laender[1]['FJ'] = "Fiji";
$laender[0]['FJ'] = "Fiji";
$laender[1]['FI'] = "Finland";
$laender[0]['FI'] = "Finland";
$laender[1]['FR'] = "France";
$laender[0]['FR'] = "Frankreich";
$laender[1]['GF'] = "French Guiana";
$laender[0]['GF'] = "Französisch Guiana";
$laender[1]['PF'] = "French Polynesia";
$laender[0]['PF'] = "Französisch Polynesien";
$laender[1]['GA'] = "Gabon";
$laender[0]['GA'] = "Gabon";
$laender[1]['GM'] = "Gambia";
$laender[0]['GM'] = "Gambia";
$laender[1]['GE'] = "Georgia";
$laender[0]['GE'] = "Georgien";
$laender[1][0] = "Germany";
$laender[0][0] = "Deutschland";
$laender[1]['GH'] = "Ghana";
$laender[0]['GH'] = "Ghana";
$laender[1]['GI'] = "Gibraltar";
$laender[0]['GI'] = "Gibraltar";
$laender[1]['GR'] = "Greece";
$laender[0]['GR'] = "Griechenland";
$laender[1]['GL'] = "Greenland";
$laender[0]['GL'] = "Grönland";
$laender[1]['GD'] = "Grenada";
$laender[0]['GD'] = "Grenada";
$laender[1]['GP'] = "Guadeloupe";
$laender[0]['GP'] = "Guadeloupe";
$laender[1]['GU'] = "Guam";
$laender[0]['GU'] = "Guam";
$laender[1]['GT'] = "Guatemala";
$laender[0]['GT'] = "Guatemala";
$laender[1]['GN'] = "Guinea";
$laender[0]['GN'] = "Guinea";
$laender[1]['GY'] = "Guyana";
$laender[0]['GY'] = "Guyana";
$laender[1]['HT'] = "Haiti";
$laender[0]['HT'] = "Haiti";
$laender[1]['VA'] = "Vatican"; $laender[0]['VA'] = "Vatikan";
$laender[1]['HN'] = "Honduras"; $laender[0]['HN'] = "Honduras";
$laender[1]['HU'] = "Hungary"; $laender[0]['HU'] = "Ungarn";
$laender[1]['IS'] = "Iceland"; $laender[0]['IS'] = "Island";
$laender[1]['IN'] = "India"; $laender[0]['IN'] = "Indien";
$laender[1]['ID'] = "Indonesia"; $laender[0]['ID'] = "Indonesien";
$laender[1]['IR'] = "Iran"; $laender[0]['IR'] = "Iran";
$laender[1]['IQ'] = "Iraq"; $laender[0]['IQ'] = "Irak";
$laender[1]['IE'] = "Ireland"; $laender[0]['IE'] = "Irland";
$laender[1]['IL'] = "Israel"; $laender[0]['IL'] = "Israel";
$laender[1]['IT'] = "Italy"; $laender[0]['IT'] = "Italien";
$laender[1]['JM'] = "Jamaica"; $laender[0]['JM'] = "Jamaika";
$laender[1]['JP'] = "Japan"; $laender[0]['JP'] = "Japan";
$laender[1]['JO'] = "Jordan"; $laender[0]['JO'] = "Jordanien";
$laender[1]['KZ'] = "Kazakstan"; $laender[0]['KZ'] = "Kasachstan";
$laender[1]['KE'] = "Kenya"; $laender[0]['KE'] = "Kenia";
$laender[1]['KI'] = "Kiribati"; $laender[0]['KI'] = "Kiribati";
$laender[1]['KW'] = "Kuwait"; $laender[0]['KW'] = "Kuwait";
$laender[1]['KG'] = "Kyrgystan"; $laender[0]['KG'] = "Kirgistan";
$laender[1]['LA'] = "Lao"; $laender[0]['LA'] = "Laos";
$laender[1]['LV'] = "Latvia"; $laender[0]['LV'] = "Lettland";
$laender[1]['LB'] = "Lebanon"; $laender[0]['LB'] = "Libanon";
$laender[1]['LS'] = "Lesotho"; $laender[0]['LS'] = "Lesotho";
$laender[1]['LI'] = "Liechtenstein"; $laender[0]['LI'] = "Liechtenstein";
$laender[1]['LT'] = "Lithuania"; $laender[0]['LT'] = "Litauen";
$laender[1]['LU'] = "Luxembourg"; $laender[0]['LU'] = "Luxemburg";
$laender[1]['MO'] = "Macau"; $laender[0]['MO'] = "Macau";
$laender[1]['MK'] = "Macedonia "; $laender[0]['MK'] = "Mazedonien";
$laender[1]['MG'] = "Madagascar"; $laender[0]['MG'] = "Madagaskar";
$laender[1]['MW'] = "Malawi"; $laender[0]['MW'] = "Malawi";
$laender[1]['MY'] = "Malaysia"; $laender[0]['MY'] = "Malaysia";
$laender[1]['MV'] = "Maldives"; $laender[0]['MV'] = "Malediven";
$laender[1]['ML'] = "Mali"; $laender[0]['ML'] = "Mali";
$laender[1]['MT'] = "Malta"; $laender[0]['MT'] = "Malta";
$laender[1]['MR'] = "Mauritania"; $laender[0]['MR'] = "Mauretanien";
$laender[1]['MU'] = "Mauritius"; $laender[0]['MU'] = "Mauritius";
$laender[1]['YT'] = "Mayotte"; $laender[0]['YT'] = "Mayotte";
$laender[1]['MX'] = "Mexico"; $laender[0]['MX'] = "Mexiko";
$laender[1]['FM'] = "Micronesia"; $laender[0]['FM'] = "Mikronesien";
$laender[1]['MD'] = "Moldova"; $laender[0]['MD'] = "Moldavien";
$laender[1]['MC'] = "Monaco"; $laender[0]['MC'] = "Monaco";
$laender[1]['MN'] = "Mongolia"; $laender[0]['MN'] = "Mongolei";
$laender[1]['MS'] = "Montserrat"; $laender[0]['MS'] = "Montserrat";
$laender[1]['MA'] = "Morocco"; $laender[0]['MA'] = "Marokko";
$laender[1]['MZ'] = "Mozambique"; $laender[0]['MZ'] = "Mosambik";
$laender[1]['MM'] = "Myanmar"; $laender[0]['MM'] = "Myanmar";
$laender[1]['NA'] = "Namibia"; $laender[0]['NA'] = "Namibia";
$laender[1]['NR'] = "Nauru"; $laender[0]['NR'] = "Nauru";
$laender[1]['NP'] = "Nepal"; $laender[0]['NP'] = "Nepal";
$laender[1]['NL'] = "Netherlands"; $laender[0]['NL'] = "Niederlande";
$laender[1]['NZ'] = "New Zealand"; $laender[0]['NZ'] = "Neuseeland";
$laender[1]['NI'] = "Nicaragua"; $laender[0]['NI'] = "Nicaragua";
$laender[1]['NE'] = "Niger"; $laender[0]['NE'] = "Niger";
$laender[1]['NG'] = "Nigeria"; $laender[0]['NG'] = "Nigeria";
$laender[1]['NU'] = "Niue"; $laender[0]['NU'] = "Niue";
$laender[1]['NF'] = "Norfolk Island"; $laender[0]['NF'] = "Norfolk Inseln";
$laender[1]['KP'] = "North Korea"; $laender[0]['KP'] = "Nord Korea";
$laender[1]['NO'] = "Norway"; $laender[0]['NO'] = "Norwegen";
$laender[1]['OM'] = "Oman"; $laender[0]['OM'] = "Oman";
$laender[1]['PK'] = "Pakistan"; $laender[0]['PK'] = "Pakistan";
$laender[1]['PW'] = "Palau"; $laender[0]['PW'] = "Palau";
$laender[1]['PA'] = "Panama"; $laender[0]['PA'] = "Panama";
$laender[1]['PG'] = "Papua New Guinea"; $laender[0]['PG'] = "Papua Neu Guinea";
$laender[1]['PY'] = "Paraguay"; $laender[0]['PY'] = "Paraguay";
$laender[1]['PE'] = "Peru"; $laender[0]['PE'] = "Peru";
$laender[1]['PH'] = "Philippines"; $laender[0]['PH'] = "Philippinen";
$laender[1]['PL'] = "Poland"; $laender[0]['PL'] = "Polen";
$laender[1]['PT'] = "Portugal"; $laender[0]['PT'] = "Portugal";
$laender[1]['PR'] = "Puerto Rico"; $laender[0]['PR'] = "Puerto Rico";
$laender[1]['RO'] = "Romania"; $laender[0]['RO'] = "Rumänien";
$laender[1]['RU'] = "Russia"; $laender[0]['RU'] = "Russland";
$laender[1]['RW'] = "Rwanda"; $laender[0]['RW'] = "Ruanda";
$laender[1]['WS'] = "Samoa"; $laender[0]['WS'] = "Samoa";
$laender[1]['SM'] = "San Marino"; $laender[0]['SM'] = "San Marino";
$laender[1]['SA'] = "Saudi Arabia"; $laender[0]['SA'] = "Saudi-Arabien";
$laender[1]['SN'] = "Senegal"; $laender[0]['SN'] = "Senegal";
$laender[1]['SC'] = "Seychelles"; $laender[0]['SC'] = "Seychellen";
$laender[1]['SL'] = "Sierra Leone"; $laender[0]['SL'] = "Sierra Leone";
$laender[1]['SG'] = "Singapore"; $laender[0]['SG'] = "Singapur";
$laender[1]['SK'] = "Slovakia"; $laender[0]['SK'] = "Slovakei";
$laender[1]['SB'] = "Solomon Islands"; $laender[0]['SB'] = "Solomon Inseln";
$laender[1]['SO'] = "Somalia"; $laender[0]['SO'] = "Somalia";
$laender[1]['ZA'] = "South Africa"; $laender[0]['ZA'] = "Südafrika";
$laender[1]['KR'] = "South Korea"; $laender[0]['KR'] = "Südkorea";
$laender[1]['ES'] = "Spain"; $laender[0]['ES'] = "Spanien";
$laender[1]['LK'] = "Sri Lanka"; $laender[0]['LK'] = "Sri Lanka";
$laender[1]['SD'] = "Sudan"; $laender[0]['SD'] = "Sudan";
$laender[1]['SR'] = "Suriname"; $laender[0]['SR'] = "Suriname";
$laender[1]['SZ'] = "Swaziland"; $laender[0]['SZ'] = "Swasiland";
$laender[1]['SE'] = "Sweden"; $laender[0]['SE'] = "Schweden";
$laender[1]['CH'] = "Switzerland"; $laender[0]['CH'] = "Schweiz";
$laender[1]['SY'] = "Syria"; $laender[0]['SY'] = "Syrien";
$laender[1]['TW'] = "Taiwan"; $laender[0]['TW'] = "Taiwan";
$laender[1]['TJ'] = "Tajikistan"; $laender[0]['TJ'] = "Tadschikistan";
$laender[1]['TZ'] = "Tanzania"; $laender[0]['TZ'] = "Tansania";
$laender[1]['TH'] = "Thailand"; $laender[0]['TH'] = "Thailand";
$laender[1]['TG'] = "Togo"; $laender[0]['TG'] = "Togo";
$laender[1]['TO'] = "Tonga"; $laender[0]['TO'] = "Tonga";
$laender[1]['TT'] = "Trinidad and Tobago"; $laender[0]['TT'] = "Trinidad und Tobago";
$laender[1]['TN'] = "Tunisia"; $laender[0]['TN'] = "Tunesien";
$laender[1]['TR'] = "Turkey"; $laender[0]['TR'] = "Türkei";
$laender[1]['TM'] = "Turkmenistan"; $laender[0]['TM'] = "Turkmenistan";
$laender[1]['TV'] = "Tuvalu"; $laender[0]['TV'] = "Tuvalu";
$laender[1]['UG'] = "Uganda"; $laender[0]['UG'] = "Uganda";
$laender[1]['UA'] = "Ukraine"; $laender[0]['UA'] = "Ukraine";
$laender[1]['AE'] = "United Arab Emirates"; $laender[0]['AE'] = "Vereinigte Arabische Emirate";
$laender[1]['GB'] = "United Kingdom"; $laender[0]['GB'] = "Vereinigtes Königreich";
$laender[1]['US'] = "United States of America"; $laender[0]['US'] = "Vereinigte Staaten von Amerika";
$laender[1]['UY'] = "Uruguay"; $laender[0]['UY'] = "Uruguay";
$laender[1]['UZ'] = "Uzbekistan"; $laender[0]['UZ'] = "Usbekistan";
$laender[1]['VU'] = "Vanuatu"; $laender[0]['VU'] = "Vanuatu";
$laender[1]['VE'] = "Venezuela"; $laender[0]['VE'] = "Venezuela";
$laender[1]['VN'] = "Vietnam"; $laender[0]['VN'] = "Vietnam";
$laender[1]['VG'] = "Virgin Islands"; $laender[0]['VG'] = "Virgin Islands";
$laender[1]['EH'] = "Western Sahara"; $laender[0]['EH'] = "Westsahara";
$laender[1]['YE'] = "Yemen"; $laender[0]['YE'] = "Jemen";
$laender[1]['YU'] = "Yugoslavia"; $laender[0]['YU'] = "Jugoslavien";
$laender[1]['ZR'] = "Zaire"; $laender[0]['ZR'] = "Zaire";
$laender[1]['ZM'] = "Zambia"; $laender[0]['ZM'] = "Sambia";
$laender[1]['ZW'] = "Zimbabwe"; $laender[0]['ZW'] = "Simbabwe";


?>
